# -*- coding: utf-8 -*-
"""reto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vVIhPOBHYPl6m34afMtNUDrWGwld5TNk

**Requisitos**:

**Analizardatos de la tienda:**

Debes evaluar información como los ingresos, las categorías más vendidas, las reseñas de los clientes, los productos más vendidos y el envío promedio.



**Crear gráficos para visualización:**

Decide qué tipos de gráficos utilizar para presentar los resultados de forma clara y visual.

Mínimo de 3 gráficos diferentes, que pueden incluir gráficos de barras, circulares, de dispersión y otros.



Enviar una recomendación:

Después del análisis, escriba un texto explicando a qué tienda debería vender el Sr. João y por qué, basándose en los datos presentados.
"""

import pandas as pd

url = "/content/drive/MyDrive/challenge1-data-science-latam-main/base-de-datos-challenge1-latam/tienda_1 .csv"
url2 = "/content/drive/MyDrive/challenge1-data-science-latam-main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "/content/drive/MyDrive/challenge1-data-science-latam-main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "/content/drive/MyDrive/challenge1-data-science-latam-main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

# Calcular el total de ingresos de la tienda 1
ingresos_t1 = tienda['Precio'].sum()
print("Ingresos totales tienda 1:", ingresos_t1)
ventas_t1 = tienda.groupby('Categoría del Producto')['Categoría del Producto'].count().sort_values(ascending=False)
print("Categorías más populares - Tienda 1:\n", ventas_t1, "\n")

ingresos_t2 = tienda2['Precio'].sum()
print("Ingresos totales tienda 2:", ingresos_t2)
ventas_t2 = tienda2.groupby('Categoría del Producto')['Categoría del Producto'].count().sort_values(ascending=False)
print("Categorías más populares - Tienda 2:\n", ventas_t2, "\n")

ingresos_t3 = tienda3['Precio'].sum()
print("Ingresos totales tienda 3:", ingresos_t3)
ventas_t3 = tienda3.groupby('Categoría del Producto')['Categoría del Producto'].count().sort_values(ascending=False)
print("Categorías más populares - Tienda 3:\n", ventas_t3, "\n")

ingresos_t4 = tienda4['Precio'].sum()
print("Ingresos totales tienda 4:", ingresos_t4)
ventas_t4 = tienda4.groupby('Categoría del Producto')['Categoría del Producto'].count().sort_values(ascending=False)
print("Categorías más populares - Tienda 4:\n", ventas_t4, "\n")

import matplotlib.pyplot as plt

cat_t1 = tienda['Categoría del Producto'].value_counts()
cat_t2 = tienda2['Categoría del Producto'].value_counts()
cat_t3 = tienda3['Categoría del Producto'].value_counts()
cat_t4 = tienda4['Categoría del Producto'].value_counts()

plt.bar(cat_t1.index, cat_t1.values, color='skyblue')
plt.title('Cantidad de Productos por Categoría (Tienda 1)')
plt.xlabel('Categoría')
plt.ylabel('Cantidad')
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

plt.bar(cat_t2.index, cat_t1.values, color='skyblue')
plt.title('Cantidad de Productos por Categoría (Tienda 2)')
plt.xlabel('Categoría')
plt.ylabel('Cantidad')
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

plt.bar(cat_t3.index, cat_t1.values, color='skyblue')
plt.title('Cantidad de Productos por Categoría (Tienda 3)')
plt.xlabel('Categoría')
plt.ylabel('Cantidad')
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

plt.bar(cat_t4.index, cat_t1.values, color='skyblue')
plt.title('Cantidad de Productos por Categoría (Tienda 4)')
plt.xlabel('Categoría')
plt.ylabel('Cantidad')
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

ventas_totale = [ingresos_t1,ingresos_t2,ingresos_t3,ingresos_t4]
tiendas = ['Tienda 1', 'Tienda 2', 'Tienda 3', 'Tienda 4']

plt.pie(ventas_totale, labels=tiendas, autopct='%1.1f%%')
plt.title('Participación de Ventas por Tienda')
plt.show()

# Calificación promedio por tienda (redondeadas a 2 decimales)
calificacion_t1 = round(tienda['Calificación'].mean(), 2)
calificacion_t2 = round(tienda2['Calificación'].mean(), 2)
calificacion_t3 = round(tienda3['Calificación'].mean(), 2)
calificacion_t4 = round(tienda4['Calificación'].mean(), 2)

# Mostrar resultados
print(" Calificación promedio tienda 1:", calificacion_t1)
print(" Calificación promedio tienda 2:", calificacion_t2)
print(" Calificación promedio tienda 3:", calificacion_t3)
print(" Calificación promedio tienda 4:", calificacion_t4)

"""Productos más vendidos y menos vendidos"""

import pandas as pd
import matplotlib.pyplot as plt

# === Productos más y menos vendidos por tienda ===

# Tienda 1
c_productos_v1 = tienda.groupby('Producto')['Producto'].count().sort_values(ascending=False)
c_productos_m1 = tienda.groupby('Producto')['Producto'].count().sort_values(ascending=True)

# Tienda 2
c_productos_v2 = tienda2.groupby('Producto')['Producto'].count().sort_values(ascending=False)
c_productos_m2 = tienda2.groupby('Producto')['Producto'].count().sort_values(ascending=True)

# Tienda 3
c_productos_v3 = tienda3.groupby('Producto')['Producto'].count().sort_values(ascending=False)
c_productos_m3 = tienda3.groupby('Producto')['Producto'].count().sort_values(ascending=True)

# Tienda 4
c_productos_v4 = tienda4.groupby('Producto')['Producto'].count().sort_values(ascending=False)
c_productos_m4 = tienda4.groupby('Producto')['Producto'].count().sort_values(ascending=True)

# === Mostrar resultados en consola ===
for i, (mas, menos) in enumerate([
    (c_productos_v1, c_productos_m1),
    (c_productos_v2, c_productos_m2),
    (c_productos_v3, c_productos_m3),
    (c_productos_v4, c_productos_m4)
], start=1):
    print(f"\n=== Tienda {i} ===")
    print("Más vendidos:")
    print(mas.head(5))
    print("\nMenos vendidos:")
    print(menos.head(5))

# === Gráficos ===
tiendas = [
    ('Tienda 1', c_productos_v1, c_productos_m1),
    ('Tienda 2', c_productos_v2, c_productos_m2),
    ('Tienda 3', c_productos_v3, c_productos_m3),
    ('Tienda 4', c_productos_v4, c_productos_m4)
]

for nombre, mas, menos in tiendas:
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    fig.suptitle(f'{nombre} - Productos más y menos vendidos', fontsize=14, fontweight='bold')

    # Más vendidos
    mas.head(5).plot(kind='bar', ax=axes[0])
    axes[0].set_title('Top 5 más vendidos')
    axes[0].set_xlabel('Producto')
    axes[0].set_ylabel('Cantidad vendida')

    # Menos vendidos
    menos.head(5).plot(kind='bar', ax=axes[1], color='orange')
    axes[1].set_title('Top 5 menos vendidos')
    axes[1].set_xlabel('Producto')
    axes[1].set_ylabel('Cantidad vendida')

    plt.tight_layout(rect=[0, 0, 1, 0.95])
    plt.show()

"""Valor del envío promedio por tienda"""

# Costo promedio de envío por tienda
gasto_envio_t1 = tienda['Costo de envío'].mean()
print("Gasto promedio envío Tienda 1:", gasto_envio_t1)

gasto_envio_t2 = tienda2['Costo de envío'].mean()
print("Gasto promedio envío Tienda 2:", gasto_envio_t2)

gasto_envio_t3 = tienda3['Costo de envío'].mean()
print("Gasto promedio envío Tienda 3:", gasto_envio_t3)

gasto_envio_t4 = tienda4['Costo de envío'].mean()
print("Gasto promedio envío Tienda 4:", gasto_envio_t4)

import numpy as np
import pandas as pd

# Datos de ejemplo
tiendas = pd.DataFrame({
    'Tienda': ['Tienda 1', 'Tienda 2', 'Tienda 3', 'Tienda 4'],
    'Ingresos': [ingresos_t1,ingresos_t2,ingresos_t3,ingresos_t4],
    'Calificacion': [calificacion_t1,calificacion_t2,calificacion_t3,calificacion_t4],
    'Envio': [gasto_envio_t1, gasto_envio_t2, gasto_envio_t3,gasto_envio_t4]
})

# Normalización 0–1
def normalizar(col):
    return (col - col.min()) / (col.max() - col.min())

tiendas['ingresos_norm'] = normalizar(tiendas['Ingresos'])
tiendas['calif_norm'] = normalizar(tiendas['Calificacion'])
tiendas['envio_norm'] = normalizar(tiendas['Envio'])

# Cálculo del puntaje
tiendas['Puntuacion'] = (
    tiendas['ingresos_norm'] * 0.6 +
    tiendas['calif_norm'] * 0.2 +
    (1 - tiendas['envio_norm']) * 0.2
)

# Mostrar resultado ordenado
print(tiendas[['Tienda', 'Puntuacion']].sort_values(by='Puntuacion', ascending=False))


plt.bar(tiendas['Tienda'], tiendas['Puntuacion'], color=['#4CAF50', '#8BC34A', '#FFC107', '#F44336'])
plt.title('Comparativo de Puntuación Total por Tienda')
plt.ylabel('Puntuación (0–1)')
plt.xlabel('Tienda')
plt.show()

"""**Informe Final
Análisis de Desempeño de Tiendas del Sr. Juan**

**Introducción**

El propósito de este análisis es determinar qué tienda debería vender el Sr. Juan, basándonos en indicadores clave de desempeño (KPI) obtenidos de los datos históricos de ventas.
Para ello, se analizaron los siguientes factores:

-Ingresos totales por tienda.

-Calificaciones promedio otorgadas por los clientes.

-Costos promedio de envío.

El análisis busca identificar cuál tienda tiene el menor rendimiento general, de modo que la venta de dicha tienda represente una decisión estratégica, ya sea para reducir pérdidas o concentrar los esfuerzos en las unidades más rentables.

Desarrollo del Análisis
1. Ingresos Totales

Los ingresos se calcularon sumando el valor total de las ventas por tienda.

Tienda 1	 1,150,880,400

Tienda 2	 1,116,343,500

Tienda 3	 1,098,019,600

Tienda 4	 1,038,375,700

Según el gráfico de barras generado, la Tienda 1 y la Tienda 2 presentan los mayores ingresos, mientras que la Tienda 4 registra los ingresos más bajos.

2. Calificación Promedio

Se analizaron las calificaciones promedio de los clientes para medir la satisfacción y reputación de cada tienda.

Tienda 1   3.98

Tienda 2	  4.04

Tienda 3	  4.05

Tienda 4	  4.00

Las tiendas 2 y 3 muestran mejor percepción del cliente, mientras que la Tienda 1 presenta la calificación más baja, pero no es tan siginificativo ya que es aceptable como una buena calificacion ya que esta por ensima de 3.5 , puede mejorar la atencion al cliente y asi subir el promedio a 4.5 que seria lo ideal en las tiendas.

3. Coste de Envío Promedio

Se calcularon los costos de envío para cada tienda con el fin de evaluar la eficiencia logística.

Tienda 1	26,018.61

Tienda 2	25,216.23

Tienda 3	24,805.68

Tienda 4	23,459.45

La Tienda 1  presenta el mayor costo promedio de envío, pero lo compensa con sus buenso resultados en ventas.

4. Puntuación Global (Normalización 0–1)

El modelo de decisión ponderado calculó el desempeño total de cada tienda según:

Ingresos (50%)

Calificación del cliente (40%)

Costo de envío (10%)

Tienda	Puntuación

Tienda 2	0.7207

Tienda 3	0.7125

Tienda 1	0.5000

Tienda 4	0.2143

El resultado indica que Tienda 2 es la mejor posicionada y Tienda 4 la de menor rendimiento.

**Conclusión y Recomendación Final**

Tras el análisis integral de las métricas y las visualizaciones obtenidas, se concluye que:

El Sr. Juan debería vender la Tienda 4, ya que presenta el peor desempeño global, con:

Menores ingresos totales.

En contraste, las Tiendas 2 y 3 son las más sólidas, con altos ingresos y satisfacción del cliente, por lo que deben mantenerse y potenciarse con estrategias de fidelización.


"""